from __future__ import annotations

from typing import Dict, List


ROUTE_KEYWORDS: Dict[str, List[str]] = {
    "network_edge_devices": [
        "router",
        "switch",
        "gateway",
        "load balancer",
        "dispositivo perimetral",
        "perimetral",
        "perimetral device",
        "edge",
        "appliance",
    ],
    "firewall": [
        "firewall",
        "cortafuegos",
        "fortigate",
        "fortinet",
        "palo alto",
        "checkpoint",
        "check point",
        "sophos",
        "sonicwall",
        "asa",
    ],
    "vpn_remote_access": [
        "vpn",
        "remote access",
        "acceso remoto",
        "ssl vpn",
        "ipsec",
        "citrix adc",
        "citrix",
        "netscaler",
        "pulse secure",
        "connect secure",
        "secure mobile access",
    ],
    "email_security": [
        "correo",
        "exchange",
        "outlook",
        "mail",
        "smtp",
        "email",
        "webmail",
        "owa",
    ],
    "web_applications": [
        "apache",
        "nginx",
        "tomcat",
        "iis",
        "sharepoint",
        "confluence",
        "jira",
        "drupal",
        "joomla",
        "wordpress",
    ],
    "identity_access": [
        "active directory",
        "ad cs",
        "ldap",
        "identity",
        "identidad",
        "sso",
        "authentication",
        "autenticación",
        "okta",
        "entra",
        "azure ad",
        "adfs",
    ],
    "windows": [
        "windows",
        "microsoft windows",
        "win32",
        ".net",
        "powershell",
    ],
    "linux_unix": [
        "linux",
        "unix",
        "ubuntu",
        "debian",
        "red hat",
        "centos",
        "kernel",
    ],
    "virtualization_cloud": [
        "vmware",
        "esxi",
        "vsphere",
        "virtualization",
        "virtualizacion",
        "hyper-v",
        "cloud",
        "nube",
        "aws",
        "azure",
        "gcp",
        "kubernetes",
        "container",
        "docker",
    ],
    "network_monitoring_management": [
        "monitoring",
        "monitorizacion",
        "manageengine",
        "zabbix",
        "nagios",
        "orion",
        "solarwinds",
        "network management",
        "prtg",
    ],
    "security_tools": [
        "edr",
        "xdr",
        "antivirus",
        "defender",
        "security center",
        "siem",
        "ids",
        "ips",
    ],
    "backup_storage": [
        "backup",
        "storage",
        "nas",
        "san",
        "veeam",
        "synology",
        "qnap",
    ],
    "mobile": [
        "android",
        "ios",
        "iphone",
        "mobile",
        "smartphone",
    ],
    "ot_iot": [
        "iot",
        "ot",
        "industrial",
        "ics",
        "scada",
        "camera",
        "camara",
        "printer",
        "impresora",
        "voip",
    ],
}

ALL_ROUTES = list(ROUTE_KEYWORDS.keys())